### ISSUE TITLE
[High] Allow preview from selecting image in 3d space

### ISSUE THREAD

**Issue by tkq66** [crslab/cloud-vision-explorer#12]
Double click thumbnail on 3D space to preview, along with camera operations. Some thoughts; it has avoid conflict with panning.

**Comment by seventwoten** [comment]
Question: Is this preview the same as the original cloud-vision behaviour, showing the full image in the main canvas? If we disabled it originally, can we enable it again? 

Side note: The original image preview also didn't bother moving the camera towards the clicked node, as the preview image blocks out most of the canvas.

**Comment by seventwoten** [comment]
Update: 

- Decided that the default behaviour will be - not zooming to an image on selection (we still have the sidebar preview)
- Add a button with the option to zoom to image. The button appears only when an image has been selected.
