### ISSUE TITLE
[Low] Center slider height offset

### ISSUE THREAD

**Issue by tkq66** [crslab/cloud-vision-explorer#7]
Slider's positioning is pushed down, so it's not at the image center. Make sure it's centered.

**Comment by sngweicong** [comment]
This is caused by reset button being coded using absolute numbers I believe. No longer a problem in CSSedits branch. 

EDIT: still is a problem, but at least we know reset button's height, be it in px or vh, affects positioning of slider

**Comment by tkq66** [comment]
I reckon you'll have to play around with position absolute and z-indexes. Have fun.
